src/objects/Certification__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User__c</referenceTo>
        <relationshipLabel>Certifications</relationshipLabel>
        <relationshipName>Certifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Certification</label>
    <nameField>
        <displayFormat>C-{0000000000}</displayFormat>
        <label>Certification Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Certifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User__c.object
<CustomObject>
    <fields>
        <fullName>Badges__c</fullName>
        <label>Badges</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Certification_URL__c</fullName>
        <label>Certification URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Points__c</fullName>
        <label>Points</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Profile_URL__c</fullName>
        <label>Profile URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Rank__c</fullName>
        <label>Rank</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trailblazer_ID__c</fullName>
        <label>Trailblazer ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trailhead_URL__c</fullName>
        <label>Trailhead URL</label>
        <type>Url</type>
    </fields>
    <label>User</label>
    <nameField>
        <displayFormat>Trailblazer-{0000000000}</displayFormat>
        <label>User ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/UpdateDataHelper.cls
/*
    Created By            :    Vishnu Kumar
    Website               :    http://0to1code.com/
*/
public class UpdateDataHelper{
    
    public UpdateDataHelper(User__c userObj){
        init(userObj);
    }
    
    private void init(User__c userObj){
        
        //Updating trailhead data
        if( string.isNotBlank( userObj.Trailhead_URL__c ) ){
            TrailheadReceiver thr = new TrailheadReceiver(userObj.Trailhead_URL__c);
            system.debug('-thr.statusCode--'+thr.statusCode);
            if( thr.statusCode == 200 ){
                userObj.Name__c = thr.name != '' ? thr.name : userObj.name;
                userObj.Title__c = thr.title != '' ? thr.title : userObj.Title__c;
                userObj.Badges__c = thr.badges != 0 ? thr.badges : userObj.Badges__c;
                userObj.Points__c = thr.points != 0 ? thr.points : userObj.Points__c;
                userObj.Profile_URL__c = thr.profileUrl != '' ? thr.profileUrl : userObj.Profile_URL__c ;
                userObj.rank__c = thr.rank;
                userObj.Trailblazer_ID__c = string.isNotBlank(userObj.Trailblazer_ID__c) ? userObj.Trailblazer_ID__c : Utility.generateRandomString(18);
            }
        }
        
        //Updating certification data
        if( String.isNotBlank(userObj.Certification_URL__c) ){
            CertificationReceiver cer = new CertificationReceiver(userObj.Certification_URL__c);
            if( cer.statusCode == 200 ){
                //Delete Existing certificates
                delete [select id, Name__c from Certification__c where user__c =: userObj.id ];
                
                //Inserting
                list<Certification__c> instCert = new list<Certification__c>();
                if( !cer.lstCerti.isEmpty() ){
                    for( CertificationReceiver.CertificationWrapper cw : cer.lstCerti ){
                        instCert.add( new Certification__c(user__c=userObj.id, name__c = cw.name ) );
                    }
                }
                
                if( !instCert.isEmpty() ){
                    insert instCert;
                }
            }
        }
        
        update userObj;
    }
}