src/objects/User__c.object
<CustomObject>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <label>Username</label>
        <type>Email</type>
    </fields>
    <label>User</label>
    <nameField>
        <displayFormat>Trailblazer-{0000000000}</displayFormat>
        <label>User ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Session.cls
/*
    Created By            :    Vishnu Kumar
    Website               :    http://0to1code.com/
*/
public class Session{
    
    public static void create(user__c usrObj){
        Cookie username = ApexPages.currentPage().getCookies().get('username');
        Cookie password = ApexPages.currentPage().getCookies().get('password');
    
        username = new Cookie('username', usrObj.username__c ,null,-1,false);
        password = new Cookie('password', usrObj.password__c ,null,-1,false);
        
        ApexPages.currentPage().setCookies(new Cookie[]{username});
        ApexPages.currentPage().setCookies(new Cookie[]{password});
    }
    
    public static UserWrapper getSession(){
        Cookie username = ApexPages.currentPage().getCookies().get('username');
        Cookie password = ApexPages.currentPage().getCookies().get('password');
        UserWrapper uw;
        
        if( username!=null && password != null ){
            uw = new UserWrapper();
            uw.username = username.getValue();
            uw.password = password.getValue();
        }
        
        return uw;
    }
    
    public static void destroy(){
        Cookie username = ApexPages.currentPage().getCookies().get('username');
        Cookie password = ApexPages.currentPage().getCookies().get('password');
    
        username = new Cookie('username', null ,null,-1,false);
        password = new Cookie('password', null ,null,-1,false);
        
        ApexPages.currentPage().setCookies(new Cookie[]{username});
        ApexPages.currentPage().setCookies(new Cookie[]{password});
    }
    
    public class UserWrapper{
        public string username;
        public string password;
    }
}