src/objects/User__c.object
<CustomObject>
    <fields>
        <fullName>Badges__c</fullName>
        <label>Badges</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Certification_URL__c</fullName>
        <label>Certification URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Facebook__c</fullName>
        <label>Facebook</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Linkedin__c</fullName>
        <label>Linkedin</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Points__c</fullName>
        <label>Points</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Profile_URL__c</fullName>
        <label>Profile URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Rank__c</fullName>
        <label>Rank</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trailblazer_ID__c</fullName>
        <label>Trailblazer ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trailhead_URL__c</fullName>
        <label>Trailhead URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Twitter__c</fullName>
        <label>Twitter</label>
        <type>Url</type>
    </fields>
    <label>User</label>
    <nameField>
        <displayFormat>Trailblazer-{0000000000}</displayFormat>
        <label>User ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/UpdateDataBatch.cls
/*
    Created By            :    Vishnu Kumar
    Website               :    http://0to1code.com/
*/
global class UpdateDataBatch implements Database.Batchable<sObject>, Database.AllowsCallouts, Schedulable{
    
    global void execute(SchedulableContext SC) {
        database.executebatch(new UpdateDataBatch(), 1);
    }


    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator( [select Name__c ,Title__c ,Profile_URL__c ,Badges__c ,Points__c, Trailblazer_ID__c ,
                                        Trailhead_URL__c ,Certification_URL__c ,Facebook__c ,Linkedin__c ,Twitter__c ,name, Rank__c  from user__c where active__c = true  AND Trailhead_URL__c!=null ] );
    }
    
    global void execute(Database.BatchableContext BC, List<sObject> scope){
        try{
        UpdateDataHelper pdh = new UpdateDataHelper((user__c)scope[0]);
        }
        catch(Exception e){}
    }
    
    global void finish(Database.BatchableContext BC){
        Utility.startUpdateDataBatch(10);
    }
}