src/objects/User__c.object
<CustomObject>
    <fields>
        <fullName>Badges__c</fullName>
        <label>Badges</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Certification_URL__c</fullName>
        <label>Certification URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Certifications__c</fullName>
        <label>Certifications</label>
        <summaryForeignKey>Certification__c.User__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Facebook__c</fullName>
        <label>Facebook</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Linkedin__c</fullName>
        <label>Linkedin</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Points__c</fullName>
        <label>Points</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Profile_URL__c</fullName>
        <label>Profile URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Rank__c</fullName>
        <label>Rank</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trailhead_URL__c</fullName>
        <label>Trailhead URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Twitter__c</fullName>
        <label>Twitter</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Website_Description__c</fullName>
        <label>Website Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Website_Name__c</fullName>
        <label>Website Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Website_URL__c</fullName>
        <label>Website URL</label>
        <type>Url</type>
    </fields>
    <label>User</label>
    <nameField>
        <displayFormat>Trailblazer-{0000000000}</displayFormat>
        <label>User ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/HomeController.cls
/*
    Created By            :    Vishnu Kumar
    Website               :    http://0to1code.com/
*/
public class HomeController{
    public list<UserWrapper> lstTopBadgeUsers{get;set;}
    public list<UserWrapper> lstTopPointsUsers{get;set;}
    public list<UserWrapper> lstTopCertUsers{get;set;}
    public list<UserWrapper> lstTopCertWeekly{get;set;}
    public integer totalActiveUsers{get;set;}

    public HomeController(){
        totalActiveUsers = 0;
        init();
    }
    
    private void init(){
        lstTopBadgeUsers = new list<UserWrapper>();
        lstTopPointsUsers = new list<UserWrapper>();
        lstTopCertUsers = new list<UserWrapper>();
        lstTopCertWeekly = new list<UserWrapper>();
         
        for( user__c usr : [Select Name__c ,Weekly_Goal__c,Title__c ,Profile_URL__c ,Badges__c ,Points__c ,Trailhead_URL__c , Certifications__c,Website_Name__c,Website_URL__c,Website_Description__c,Weekly_Earned__c,
                            Certification_URL__c ,Facebook__c ,Linkedin__c ,Twitter__c ,Rank__c,name from User__c where name__c != null AND active__c = true order by Badges__c desc Nulls last,Points__c  desc,Certifications__c desc limit 5] ){
            lstTopBadgeUsers.add( new UserWrapper(usr) );
        }
        
        for( user__c usr : [Select Name__c ,Weekly_Goal__c,Title__c ,Profile_URL__c ,Badges__c ,Points__c ,Trailhead_URL__c , Certifications__c,Website_Name__c,Website_URL__c,Website_Description__c,Weekly_Earned__c,
                            Certification_URL__c ,Facebook__c ,Linkedin__c ,Twitter__c ,Rank__c,name from User__c where name__c != null AND active__c = true  order by Points__c  desc  Nulls last,Badges__c desc,Certifications__c desc limit 5] ){
            lstTopPointsUsers.add( new UserWrapper(usr) );
        }
        
        for( user__c usr : [Select Name__c ,Weekly_Goal__c,Title__c ,Profile_URL__c ,Badges__c ,Points__c ,Trailhead_URL__c , Certifications__c,Website_Name__c,Website_URL__c,Website_Description__c,Weekly_Earned__c,
                            Certification_URL__c ,Facebook__c ,Linkedin__c ,Twitter__c ,Rank__c,name from User__c where name__c != null AND active__c = true  AND Certifications__c > 0 order by Certifications__c desc, Badges__c desc ,Points__c desc  limit 5] ){
            lstTopCertUsers.add( new UserWrapper(usr) );
        }
        
        for( user__c usr : [Select Name__c ,Weekly_Goal__c,Title__c ,Profile_URL__c ,Badges__c ,Points__c ,Trailhead_URL__c , Certifications__c,Website_Name__c,Website_URL__c,Website_Description__c,Weekly_Earned__c,
                            Certification_URL__c ,Facebook__c ,Linkedin__c ,Twitter__c ,Rank__c,name from User__c where name__c != null AND active__c = true  order by Weekly_Earned__c desc Nulls last, Badges__c desc Nulls last ,Points__c desc  limit 5] ){
            lstTopCertWeekly.add( new UserWrapper(usr) );
        }
    }
    

    
    public class UserWrapper{
        public user__c usrObj{get;set;}
        public decimal achievedWeeklyGoal{get;set;}
        
        public UserWrapper(user__c usrObj){
            this.usrObj = usrObj;
            
            if( usrObj.Weekly_Goal__c != null && usrObj.Weekly_Goal__c != 0 && usrObj.Weekly_Earned__c != null ){
                achievedWeeklyGoal =  (usrObj.Weekly_Earned__c/usrObj.Weekly_Goal__c)*100 ;
            }
        }
    }
}