src/objects/User__c.object
<CustomObject>
    <fields>
        <fullName>Badges__c</fullName>
        <label>Badges</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Certification_URL__c</fullName>
        <label>Certification URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Certifications__c</fullName>
        <label>Certifications</label>
        <summaryForeignKey>Certification__c.User__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Facebook__c</fullName>
        <label>Facebook</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Linkedin__c</fullName>
        <label>Linkedin</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Points__c</fullName>
        <label>Points</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Profile_URL__c</fullName>
        <label>Profile URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Rank__c</fullName>
        <label>Rank</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trailblazer_ID__c</fullName>
        <label>Trailblazer ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trailhead_URL__c</fullName>
        <label>Trailhead URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Twitter__c</fullName>
        <label>Twitter</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <label>Username</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Website_Description__c</fullName>
        <label>Website Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Website_Logo_URL__c</fullName>
        <label>Website Logo URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Website_Name__c</fullName>
        <label>Website Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Website_URL__c</fullName>
        <label>Website URL</label>
        <type>Url</type>
    </fields>
    <label>User</label>
    <nameField>
        <displayFormat>Trailblazer-{0000000000}</displayFormat>
        <label>User ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProfileController.cls
/*
    Created By            :    Vishnu Kumar
    Website               :    http://0to1code.com/
*/
public class ProfileController{
    public user__c usrObj{get;set;}
    public string userId{get;set;}
    
    public ProfileController(){
        usrObj = new user__c();
    }
    
    public void init(){
        if( string.isNotBlank(userId) ){
            usrObj = [select Name__c ,Title__c ,Profile_URL__c, active__c,Badges__c ,Points__c , Certifications__c, Username__c, Password__c, Website_Name__c, Website_Description__c,
                      Website_URL__c, Website_Logo_URL__c,
                      Trailhead_URL__c ,Certification_URL__c ,Weekly_Goal__c, Trailblazer_ID__c ,Facebook__c ,Linkedin__c ,Twitter__c ,name, Rank__c  from user__c where id =: userId ];
        }
        else{
            usrObj = new user__c();
        }        
    }
    
    public void login(){
        try{
            list<user__c> lstUser = [select username__c,password__c,active__c from user__c where username__c =: usrObj.username__c ];
            
            if( !lstUser.isEmpty() ){
                if( lstUser[0].password__c == usrObj.password__c ){
                    userId = lstUser[0].id;
                    PageMessage.addMessage(PageMessage.INfo, 'Logged in successfully.' );
                    PageMessage.addMessage(PageMessage.INfo, 'Seesion will be destroyed if you refresh the page. In this case please login again.' );
                    init();
                }
                else{
                    PageMessage.addMessage(PageMessage.Error, 'Password is incorrect.' );
                }
            }
            else{
                insert usrObj;
                userId = usrObj.id;
                PageMessage.addMessage(PageMessage.INfo, 'Welcome to the Trailhead and Certification board!!!!' );
                PageMessage.addMessage(PageMessage.INfo, 'Seesion will be destroyed if you refresh the page. In this case please login again.' );

                init();
            }
        }
        catch(Exception e){
            PageMessage.addMessage(PageMessage.Error, e.getMessage() );
        }
    }
    
    public PageReference logout(){
        PageReference pg = new PageReference('/apex/home');
        pg.setRedirect(true);
        return pg;
    }
    
    public void save(){
        try{
            usrObj.active__c =true;
            update usrObj;
            init();
        }
        catch(Exception e){
            PageMessage.addMessage(PageMessage.Error, e.getMessage() );
        }
    }
    
    public void initRefresh(){
        try{
            UpdateDataHelper udh = new UpdateDataHelper(usrObj);
            init();
        }
        catch(Exception e){
            PageMessage.addMessage(PageMessage.Error, e.getMessage() );
        }
    }
}