src/objects/User__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <label>Username</label>
        <type>Email</type>
    </fields>
    <label>User</label>
    <nameField>
        <displayFormat>Trailblazer-{0000000000}</displayFormat>
        <label>User ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/HeaderComponent.cls
/*
    Created By            :    Vishnu Kumar
    Website               :    http://0to1code.com/
*/
public class HeaderComponent{
    public user__c usrObj{get;set;}

    public HeaderComponent(){
        init();
    }
    
    public void init(){
        Session.UserWrapper uw = Session.getSession();
        usrObj = new user__c();
        
        if( uw != null ){
            list<user__c> lstUser = [select username__c,password__c,name__c from user__c where username__c =: uw.username ];
            
            if( !lstUser.isEmpty() ){
                if( lstUser[0].password__c == uw.password ){
                    usrObj = lstUser[0];
                }
            }
        }
    }
}