src/objects/User__c.object
<CustomObject>
    <fields>
        <fullName>Badges__c</fullName>
        <label>Badges</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Certifications__c</fullName>
        <label>Certifications</label>
        <summaryForeignKey>Certification__c.User__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Points__c</fullName>
        <label>Points</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Twitter__c</fullName>
        <label>Twitter</label>
        <type>Url</type>
    </fields>
    <label>User</label>
    <nameField>
        <displayFormat>Trailblazer-{0000000000}</displayFormat>
        <label>User ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Z_SocialHandlesCtrl.cls
Public Class Z_SocialHandlesCtrl{
    public string twitterNames{get;set;}
    
    public void getAllTwitter(){
        twitterNames = '';
        fillString( filldata([select id, Twitter__c  from User__c where Twitter__c  != null ]) );
    }
    
    public void top5(){
        set<string> setOfnm = filldata([select id, Twitter__c  from User__c where Twitter__c  != null AND name__c != null order by Badges__c desc,Points__c  desc,Certifications__c desc limit 5 ]);
        setOfnm.addAll( filldata([select id, Twitter__c  from User__c where Twitter__c  != null AND name__c != null order by Points__c  desc,Badges__c desc,Certifications__c desc limit 5]) );
        setOfnm.addAll( filldata([select id, Twitter__c  from User__c where Twitter__c  != null AND name__c != null AND Certifications__c > 0 order by Certifications__c desc, Badges__c desc ,Points__c desc  limit 5]) );
        setOfnm.addAll( filldata([select id, Twitter__c  from User__c where Twitter__c  != null AND name__c != null AND Weekly_Earned__c > 0 order by Weekly_Earned__c desc, Badges__c desc ,Points__c desc  limit 5]) );

        fillString(setOfnm);
    }
    
    private set<string> filldata( list<User__c> lstUser ){        
        set<string> setOfName = new set<string>();
        for( user__c u : lstUser ){
            string tw = u.Twitter__c;
            string tname = tw.substring(tw.indexOf('.com/')+5,tw.length());
            setOfName.add('@'+tname);
        }
        return setOfName; 
    }
    
    private void fillString( set<string> setOfName ){
        string temp = '';
        for( string tname : setOfName ){
            temp += tname+' ';
            
            if( temp.length() > 260 ){
                twitterNames += temp + '\n\n';
                temp = '';
            } 
        }
        
        if( temp != '' ){
            twitterNames += temp + '\n\n';
        }
    }
}